### PR TITLE
Fix issue 3760

### LINKED ISSUE #3760: Navbar's Dropdown Not Being Hoverable After Adding Collapsible
### Overview of the problem

**Buefy** version: [0.9.21]
**Vuejs** version: [2.7.8]
**Windows 11/Firefox**:

### Description

Navbar's dropdown not being hoverable after adding collapsible

### Steps to reproduce

`
<b-navbar-dropdown label="Programme" boxed hoverable collapsible>
	<b-navbar-item href="#">
		TVET
	</b-navbar-item>
	<b-navbar-item href="#">
		Academic
	</b-navbar-item>
</b-navbar-dropdown>
`

### Expected behavior

Being hoverable on computer, also being collapsible on mobile

### Actual behavior

[https://codepen.io/zhaolinlau/pen/YzaYKXg](https://codepen.io/zhaolinlau/pen/YzaYKXg)

### PR DESCRIPTION
**Pull request by geeksilva97**
This pr Fixes #3760 

## Proposed Changes

- Check collapsible condition only when on mobile

### Demo

https://user-images.githubusercontent.com/15680379/194452930-293fa27f-b73c-49e7-83fa-a945ae1818fd.mov

### CODE REVIEW

File: src/components/navbar/NavbarDropdown.vue [hunk 1]
```diff
@@ -73,6 +82,7 @@ export default {
     },
     watch: {
         active(value) {
+            console.log({ value, isHoverable: this.isHoverable, collapsible: this.collapsible })
             this.newActive = value
```
Comment (jtommy) [inline src/components/navbar/NavbarDropdown.vue:86]: Please remove it

**Review by jtommy — CHANGES_REQUESTED** [review]

File: src/components/navbar/NavbarDropdown.vue (hunk 1 above)
Comment (geeksilva97) [reply src/components/navbar/NavbarDropdown.vue:86]: sure. My bad

**Review by jtommy — APPROVED** [review]
