### PR TITLE
insure getValueByPath successfully returns

### LINKED ISSUE #1862: unable to reliably sort on nested property
### Overview of the problem

Sorting is inconsistent when using nested properties. In the case we are accessing a property on an undefined nested object there is an error when trying to access an index on null

**Buefy** version: [0.8.5]
**Vuejs** version: [2.5.2]
**OS/Browser**: Windows 10 Version 1803, Build 17134.1006 / Chrome Version 77.0.3865.120

### Description

Sorting fails when a nested object's property is not defined for all rows. 

For example this table will fail to sort the Nested Prop column:

```vue
<template>
  <div id="main">
    <b-table :data="data">
      <template slot-scope="data">
        <b-table-column 
          field="name" 
          label="Name" 
          sortable>
          {{ data.row.name }}
        </b-table-column>
        <b-table-column
          field="nested.prop"
          label="Nested Prop"
          sortable>
          {{ safeValueAccess(data.row, 'nested.prop') }}
        </b-table-column>
      </template>
    </b-table>
  </div>
</template>

<script>
export default {
  name: "App",
  components: {},
  data() {
    return {
      data: [
        { name: "item 1", nested: { prop: "Hello, World!" } },
        { name: "item 2" },
        { name: "item 3" }
      ]
    };
  },
  methods: {
    safeValueAccess(object, path) {
      return path.split(".").reduce((o, i) => (o || {})[i], object);
    }
  }
};
</script>

<style>
#main {
  padding: 50px;
}
</style>
```

### Steps to reproduce

See sandbox code: https://codesandbox.io/s/buefy-playground-x20uz

### Expected behavior

Column sorting should work the same as it does for any other undefined values

### Actual behavior

Sorting fails, echoing the error to the console:
```
TypeError: Cannot read property 'prop' of undefined
```

### PR DESCRIPTION
**Pull request by willhatchVista**
insure that getValueByPath always returns a value without throwing an error caused by missing nested objects

Fixes #

Fixes #1862 

## Proposed Changes

-improve reliability of getValueByPath helper function, insuring it does not throw error on null nested object
-
-

### CODE REVIEW

**Comment by willhatchVista** [comment]
I'm confused by the linter error, as I didn't add any braces: 
/home/circleci/repo/src/utils/helpers.js
  5:33  error  Missing space before opening brace  space-before-blocks

File: src/utils/helpers.js [hunk 1]
```diff
@@ -2,8 +2,10 @@
  * Get value of an object property/path even if it's nested
  */
 export function getValueByPath(obj, path) {
-    const value = path.split('.').reduce((o, i) => o[i], obj)
-    return value
+    if (typeof obj === 'object') {
```
Comment (jtommy) [inline src/utils/helpers.js]: I think it's no correct add this check

Comment (willhatchVista) [reply src/utils/helpers.js]: I wasn't sure if this helper might ever have a type passed in that would throw an error when accessing the index. I think this would happen in case of int being passed in

Comment (jtommy) [reply src/utils/helpers.js]: In case of string or other it'll return null value

Comment (willhatchVista) [reply src/utils/helpers.js]: thank you! updating to reflect

**Comment by jtommy** [comment]
Thanks
