### PR TITLE
Autocomplete keyboard navigation enhancement

### LINKED ISSUE #3437: Keyboard Navigation for Header and Footer Slots of Autocompletes
### Overview of the problem

**Buefy** version: [0.9.8]
**Vuejs** version: [2.6.12]
**OS/Browser**: Chome and Edge

### Description
The Header and Footer slots of autocompletes can not be navigated to with the arrow keys. Currently, it can only be selected by a mouse. I believe this is incorrect and the option to use arrow keys should exist.

no-keyboard-navigation-header

### Steps to reproduce

1.Open an autocomplete with a header or footer slot.
2.Attempt to navigate to the header or footer slot.

### Expected behavior

I believe that the header and footer slots should be able to be navigated to with arrow keys. When the Keep-First option is selected the first result should still be the one hovered. However, the user should be able to hit the up arrow to navigate to the header item.

### Actual behavior
The ability to navigate to the header and footer slots is not present.

### PR DESCRIPTION
**Pull request by JDurman**
Fixes #3437

## Proposed Changes

- Header and footer slots for autocompletes can now be navigated to with a keyboard.
- Added a select-header and select-footer event. This can be used to call a function when the appropriate slot is selected.
- I also added the keep-first and open-on-focus to the header example in the documentation so that people can see how the behavior interacts with the new slot behavior.

### CODE REVIEW

File: src/components/autocomplete/Autocomplete.vue [hunk 1]
```diff
@@ -38,9 +38,16 @@
                     class="dropdown-content"
                     v-show="isActive"
                     :style="contentStyle">
-                    <div v-if="hasHeaderSlot" class="dropdown-item">
+                    <a
+                        v-if="hasHeaderSlot"
+                        class="dropdown-item"
+                        role="button"
+                        tabindex="0"
+                        :class="{ 'is-hovered': 'header' === hovered }"
```
Comment (jtommy) [inline src/components/autocomplete/Autocomplete.vue:46]: What happen if an option value is "header" or "footer" ?

File: src/components/autocomplete/Autocomplete.vue [hunk 2]
```diff
@@ -38,9 +38,16 @@
...
+                        @click="setSelected('header', undefined, $event)"
```
Comment (jtommy) [inline src/components/autocomplete/Autocomplete.vue:47]: Why don't you emit 'select-header' instead of call `setSelected` ?

**Review by jtommy — CHANGES_REQUESTED** [review]
I didn't try but reading the code there are a few things to change, please check my review.
Also it adds breaking changes, for example the replacing from `div` to `a` and the header and footer are now always selectable (probably better to add two props that enable that behaviour)

File: src/components/autocomplete/Autocomplete.vue [hunk 3]
```diff
@@ -78,9 +85,16 @@
                         class="dropdown-item is-disabled">
                         <slot name="empty" />
                     </div>
-                    <div v-if="hasFooterSlot" class="dropdown-item">
+                    <a
+                        v-if="hasFooterSlot"
+                        class="dropdown-item"
+                        role="button"
+                        tabindex="0"
+                        :class="{ 'is-hovered': 'footer' === hovered }"
```
Comment (jtommy) [inline src/components/autocomplete/Autocomplete.vue:93]: I am not sure about it.. is it a good to show the item with with hovered class? I should try it before..

**Comment by jtommy** [comment]
@JDurman did you read my review ?

**Comment by JDurman** [comment]
@jtommy Yes, I did. I am currently working on implementing your suggestions. I added two props for making it selectable or not. The last thing I am working on is fixing the select event. I should finish it today.

File: src/components/autocomplete/Autocomplete.vue (hunk 1 above)
Comment (JDurman) [reply src/components/autocomplete/Autocomplete.vue]: Yes, this would be an issue. I am resolving this now by using an internal variable for managing the state of hover for the header/footer and leaving the hovered variable for just items in the list.

File: src/components/autocomplete/Autocomplete.vue (hunk 3 above)
Comment (JDurman) [reply src/components/autocomplete/Autocomplete.vue]: I think it needs the hover effect otherwise it's very hard to tell when you have the header or footer selected.

File: src/components/autocomplete/Autocomplete.vue (hunk 2 above)
Comment (JDurman) [reply src/components/autocomplete/Autocomplete.vue]: Your question made me realize that setSelected was probably not the best function to be handling this event since it won't actually be setting a value. I went ahead and made a function for it instead that handles both the confirm keys and click event.

File: src/components/autocomplete/Autocomplete.vue (hunk 3 above)
Comment (JDurman) [reply src/components/autocomplete/Autocomplete.vue]: To clarify I made it so that it only shows the hover when using the arrow keys. It won't show when hovered by a mouse.

**Review by jtommy — APPROVED** [review]

**Comment by jtommy** [comment]
@JDurman thanks 👍
