### PR TITLE
Autocomplete enhancements and fixes for accessibility

### LINKED ISSUE #3357: Autocomplete with
### Overview of the problem

**Buefy** version: 0.9.7
**Vuejs** version: 2.6.13
**OS/Browser**: Windows 10, Firefox 89

### Description

An Autocomplete with `keep-first` will trigger `@select` for the currently selected element when clicking outside.

### Steps to reproduce

```vue
<template>
  <div id="app">
    <b-autocomplete
      :data="statuses"
      field="name"
      keep-first
      :open-on-focus="true"
      @select="selected = $event"
    >
      <template slot-scope="props">
        {{ props.option.name }}
      </template>
    </b-autocomplete>

    <div>
      Selected: {{selected}}
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      selected: null,
      statuses: [
        {
          status: "one",
          name: "One"
        },
        {
          status: "two",
          name: "Two"
        },
        {
          status: "three",
          name: "Three"
        },
        {
          status: "four",
          name: "Four"
        },
        {
          status: "five",
          name: "Five"
        }
      ]
    };
  }
};
</script>
```

Click on the Autocomplete, then click outside to close it.

### Expected behavior

`selected` stays `null`

### Actual behavior

`selected` becomes the last selected item.

### PR DESCRIPTION
**Pull request by elisamuelps**
# Autocomplete
## Bug Fixes
- Fixed Bug when pressing esc which briefly toggled/expanded the suggestion list
- Moved esc input event from key up to key down
- Use of keycodes to detect esc, tab and enter keys
## Accesibility
- Add aria-autocomplete to the input element as "list" or "both" depending if keep-first is enabled or not
- Add native-search prop which changes the input element's type to "search" or "text"

# Documentation
## Autocomplete
- Added example of Keep First and select on clicking outside

# Fixes
Fixes #3357 

## Proposed Changes
It is all on my changelog above

### CODE REVIEW

**Comment by elisamuelps** [comment]
Please check in the new documentation, I added Buefy 0.9.9 but I'm not sure if you will release it under 0.9.8.1 or 0.9.9

Glad to Help!

**Comment by elisamuelps** [comment]
Just updated the jest snapshot for the autocomplete element since adding the accessibility functionality adds an extra aria element and also the esc key was not being triggered when using keycodes, so I made the element to detect both keycodes and key names

**Comment by jtommy** [comment]
@elisamuelps 
why did you convert key to which ?

**Comment by elisamuelps** [comment]
I did a mistake :( though that by using which it would help with different keyboard layouts, javascript is weird, but I'm reading that is being deprecated, I will solve it now. Hold on.

**Comment by elisamuelps** [comment]
@jtommy itd all sorted, removed which from the pr, I tested the implementation and it performs as expected.

**Comment by elisamuelps** [comment]
I have to amend the changelog above, going to type it below:

# Autocomplete
## Bug Fixes
- Fixed Bug when pressing Escape/Tab which briefly toggled/expanded the suggestion list
- Moved Escape input event from key up to key down
## Accessibility
- Add aria-autocomplete to the input element as "list" or "both" depending if keep-first is enabled or not
- Add native-search prop which changes the input element's type to "search" or "text"

# Documentation
## Autocomplete
- Added example of Keep First and select on clicking outside

**Comment by jtommy** [comment]
@elisamuelps now it's ok, thanks.
What's the advantage to use search as input type ?

**Comment by elisamuelps** [comment]
It is more about accessibility: line breaks are also automatically disabled when search is used instead of text and also it helps screen readers to identify the object. In fact, the autocomplete component is more of a search box than a text box. Although both look similar.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/search

**Comment by elisamuelps** [comment]
Thing is, because Vue forms use client side rendering, a 200 get request with a search query is not commonly performed which adds autocompletion of recent searches and I fear whether or not they clash with the list, if so, I can put the native html search form to use inside of the component. It will help people to be W3C compliant.

**Comment by jtommy** [comment]
@elisamuelps We might add search type as default, what do you think?

**Comment by elisamuelps** [comment]
That would be the best solution, we can get rid of one prop and treat the element as a native html search input which is more compliant with the W3C. If there isn't any reason to keep using text I'd say is good to make the change. I can make another commit later to reflect on the change.

**Comment by jtommy** [comment]
It could be a breaking change.. but I don't like the new prop if search type is a good approach

**Comment by elisamuelps** [comment]
Yeah me neither, I went originally with the prop idea because I didn't wanted to change the existing functionality, but if there is the possibility to switch the autocomplete input to search I will gladly add the implementation.

**Comment by elisamuelps** [comment]
Hey @jtommy Been researching a bit, there is more into autocomplete elements than previously though, I additionally checked Google's implementation of their native input and to my wonder they use text instead of search. 

I found that we are going to be fine as long as we use the right aria elements, because there are more cons than pros of using the <datalist> and <options> elements. One of them is not being able to style those components and the other is not being able to provide a prop which is sad because you cannot add icons or any content inside of the list. In a resume: it is not worth doing datalist or input type search at all. 

The only thing we miss by not using the search input type is that the browser automatically saves your most recent searches first but the later can be done without any change to the component at all, that's what the slots are there for.

It is kind of sad because I wanted to improve the element and I ended up rolling back most changes, however, I did fixed #3185 and the library will benefit from it

I left also the type for those who still want to play around with the native input type element.

Hit me up if you need anything else, I have tested the changes and it is all solid now.

File: src/components/autocomplete/Autocomplete.vue [hunk 1]
```diff
@@ -308,6 +310,12 @@ export default {
             this.$emit('input', value)
             // Check if selected is invalid
             const currentValue = this.getValue(this.selected)
+
+            // Fixes #3185
+            if (!currentValue) {
```
Comment (jtommy) [inline src/components/autocomplete/Autocomplete.vue:315]: Better a typeof undefined check and an else if ;)

Comment (elisamuelps) [reply src/components/autocomplete/Autocomplete.vue:315]: Hi @jtommy I have been busy with the release of a project :( but I will have a look tomorrow and submit a commit.

By the way, I found that strict type checking has some bugs with specific minifier settings, for example google closure compiler and terser with the option of booleans as integers will trigger errors with Buefy because of the strict type checking. Everything else runs as expected.

**Comment by dauriata** [comment]
to fix one of the bug mentionned in #3469 (option still selected even if there is no match), I propose to modify the `selectFirstOption` like this in `Autocomplete.vue`: 

```
        /**
         * Select first option
         */
        selectFirstOption(computedData) {
            this.$nextTick(() => {
                if (computedData.some((element) => element.items && element.items.length)) {
                    // If has visible data or open on focus, keep updating the hovered
                    const option = computedData[0].items[0]
                    if (this.openOnFocus || (this.newValue !== '' && this.hovered !== option)) {
                        this.setHovered(option)
                    }
                } else {
                    this.setHovered(null)
                }
            })
        },
```

I am not opening a new PR cause I think it could fit well in this one. 
the previous test `if(element.length)` should mimic the `isEmpty` function, I guess it has not been updated when the Groups feature was introduced.

**Comment by jtommy** [comment]
@dauriata open a PR please
