### PR TITLE
Cast number type value to number when emit input event in BInput

### LINKED ISSUE #3109: b-numberinput incorrect handling of negative numbers between 0 and -1
### Overview of the problem

**Buefy** version: 0.9.4
**Vuejs** version: 2.6.11
**OS/Browser**: OSx / Firefox

### Description
It's impossible to enter negative numbers between 0 and -1 in b-numberinput.

### Steps to reproduce
1. Go to https://buefy.org/documentation/numberinput
2. Try entering -0.3, as soon as you hit the 0 key the negative sign will be removed and the number will be made positive

### Expected behavior
Starting a number with - should not mutate that number to positive.

### Actual behavior
Number becomes positive while it should be negative as the user started entering the number with a - sign

### PR DESCRIPTION
**Pull request by yuwu9145**
Fixes #3109

## Proposed Changes

- This issue is caused by this [vue behaviour](https://github.com/vuejs/vue/issues/11897)
- As per the answer in [vue behaviour](https://github.com/vuejs/vue/issues/11897), `.number` only work on native `v-model`, not on custom components. So `.number` is removed from `v-model` in `b-input`, instead `NumberInput` will be responsible to do number casting when it emits `@input`.

### CODE REVIEW

File: src/components/numberinput/Numberinput.vue [hunk 1]
```diff
@@ -153,7 +153,9 @@ export default {
                     }
                 }
                 this.newValue = newValue
-                this.$emit('input', newValue)
+                if (!isNaN(newValue) && newValue !== null && newValue !== '-0') {
```
Comment (yuwu9145) [inline src/components/numberinput/Numberinput.vue:156]: Purpose is only emit when `newValue` can be cast to a valid number, also `-0` will be cast to `0` without negative sign which will cause input becomes 0, so this case is ignored here.

**Comment by yuwu9145** [comment]
Hi @jtommy , sorry for bothering. Just want to reach out to see if there is an ETA to review this pull request? :)

**Comment by jtommy** [comment]
@yuwu9145 i don't understand -0 to be honest

**Comment by yuwu9145** [comment]
> @yuwu9145 i don't understand -0 to be honest

When it comes to `v-model`, if `value` part is `-0`, it is a legitimate number `Number(-1) === -1`. However, Vue will set convert any number to string before update the `input` dom using `String(value)`. Then `String(-0) === '0'`. So `-0` should be specially treated

**Comment by yuwu9145** [comment]
@jtommy Here is a [demo link](https://codepen.io/yuchaosydney/pen/poNREOE) that simulates this `-0` issue with Vue only
