### PR TITLE
Fix #1951: Modal a11y improvements

### LINKED ISSUE #1951: Trouble with trap-focus in modal
### Overview of the problem

I saw the trap-focus prop was added to the Modal component in 0.8.6, which is great! This is an accessibility win and I might even suggest enabling it by default at some point in the future. I'm having a problem, though - even when I set it to true, I don't see the correct behavior. Here's my example pen: https://codepen.io/dalton/pen/BaaYNGJ

As you can see, after you hit the button and then hit tab a couple of times, you're still focused on the background page, not in the modal. 

Am I doing something wrong, and would there be a way to focus on the close button upon opening the modal, similar to [Micromodal](https://micromodal.now.sh/)?

Cheers.

**Buefy** version: 0.8.6
**Vuejs** version: latest

### PR DESCRIPTION
**Pull request by service-paradis**
Fixes #1951

## Proposed Changes

- Fix Modal close button to be focusable (using `v-show` instead of `v-if` so it exists when the directive is bind)
- Give focus to the modal element on open so focus is inside modal when tabbing
- Remove focus within bind function (element is not yet displayed when bind is called, so it is not useful)

### CODE REVIEW

File: src/components/modal/Modal.vue [hunk 1]
```diff
@@ -8,6 +8,7 @@
             class="modal is-active"
             :class="[{'is-full-screen': fullScreen}, customClass]"
             v-trap-focus="trapFocus"
+            tabindex="-1"
```
Comment (service-paradis) [inline src/components/modal/Modal.vue]: I added this so we can trigeer `focus()` on the element.

File: src/components/modal/Modal.vue [hunk 2]
```diff
@@ -27,7 +28,8 @@
                 <slot v-else/>
                 <button
                     type="button"
-                    v-if="showX && !animating"
+                    v-if="showX"
+                    v-show="!animating"
```
Comment (service-paradis) [inline src/components/modal/Modal.vue]: I use `v-show` instead of `v-if` because I want to be able to focus on the close button when using `trap-focus`. When we use `v-if`, the element does not exist within the `bind` function of the `trapFocus` directive.

File: src/components/modal/Modal.vue [hunk 3]
```diff
@@ -133,6 +135,11 @@ export default {
     watch: {
         active(value) {
             this.isActive = value
+            this.$nextTick(() => {
+                if (value && this.$el && this.$el.focus) {
+                    this.$el.focus()
+                }
+            })
```
Comment (service-paradis) [inline src/components/modal/Modal.vue]: This is to give the focus to the element. If we dont do this, once we open the modal and we use `TAB`, the focus is not given within the modal. Take this eample:
https://codepen.io/dalton/pen/BaaYNGJ

**Comment by jtommy** [comment]
Thanks!
